const $=id=>document.getElementById(id);
let zips=[],dmas=[],dmaGeo=null,map,layerGroup,selectedZips=[],activeDMA=null;
const catLabel={hvac:'HVAC',roofing:'Roofing',windows:'Windows & Doors'};
function norm(s){return (s||'').toLowerCase().replace(/dma/g,'').replace(/fort /g,'ft ').replace(/saint /g,'st ').replace(/[^a-z0-9]/g,'')}
const aliases={
  'miamiftlauderdale':'miamiftlauderdale',
  'tampastpetersburg':'tampastpetesarasota',
  'orlandodaytonabeachmelbourne':'orlandodaytonabchmelbrn',
  'sanfranciscooaklandsanjose':'sanfranciscooaklandsanjose',
  'hartfordnewhaven':'hartfordnewhaven',
  'washingtondc':'washingtondchagrstwn',
  'clevelandakron':'clevelandakroncanton',
  'wilkesbarrescranton':'wilkesbarrescrantonhztn'
};
function fmt(n){return Math.round(n||0).toLocaleString()}
function avg(a,k){return a.length?a.reduce((s,x)=>s+(+x[k]||0),0)/a.length:0}
function wavg(a,k,w='owner_hh'){const d=a.reduce((s,x)=>s+(+x[w]||0),0);return d?a.reduce((s,x)=>s+(+x[k]||0)*(+x[w]||0),0)/d:0}
function wavgNested(a,obj,key){const d=a.reduce((s,x)=>s+(+x.owner_hh||0),0);return d?a.reduce((s,x)=>s+(+x[obj]?.[key]||0)*(+x.owner_hh||0),0)/d:0}
function hav(a,b){const R=3958.8,rad=x=>x*Math.PI/180,dlat=rad(b.lat-a.lat),dlon=rad(b.lon-a.lon);const q=Math.sin(dlat/2)**2+Math.cos(rad(a.lat))*Math.cos(rad(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function pointInRing(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi+1e-12)+xi))inside=!inside}return inside}
function pointInGeom(z,g){if(!g)return false;const polys=g.type==='Polygon'?[g.coordinates]:g.coordinates;for(const p of polys){if(pointInRing(z.lon,z.lat,p[0]))return true}return false}
function geoForDMA(name){if(!dmaGeo)return null;const n=aliases[norm(name)]||norm(name);let exact=dmaGeo.features.find(f=>norm(f.properties.NAME)===n);if(exact)return exact;return dmaGeo.features.find(f=>{const x=norm(f.properties.NAME);return x.includes(n)||n.includes(x)})}
function color(v){return v>=75?'#17324d':v>=60?'#315c7d':v>=45?'#6f91aa':v>=30?'#a8bbc8':'#d9e2e7'}
function mapVal(x){const m=$('metric').value,c=$('category').value;if(m==='need')return typeof x.need==='number'?x.need:(x.need?.[c]??0);if(m==='score')return typeof x.score==='number'?x.score:(x.score?.[c]??0);if(m==='owner_hh')return Math.min(100,Math.sqrt((x.owner_hh||0))/4);return +x[m]||0}
function initMap(){map=L.map('map',{zoomControl:true}).setView([39,-98],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);layerGroup=L.layerGroup().addTo(map)}
function dmaRank(){const c=$('category').value;return dmas.map(d=>{const x=d[c]||{};return {...d,index:x.index||0,planned:x.planned||0,base:x.base||0}}).sort((a,b)=>b.index-a.index)}
function renderDMA(){activeDMA=null;selectedZips=[];$('tableTitle').textContent='DMA Rankings';$('tableSub').textContent='Scarborough planned next-12-month demand. Select a DMA to calculate local household opportunity.';$('thead').innerHTML='<tr><th>DMA</th><th>Intent Index</th><th>Planned HH</th><th>Base HH</th></tr>';const rows=dmaRank().slice(0,+$('topN').value);$('tbody').innerHTML=rows.map(r=>`<tr data-dma="${r.dma}"><td>${r.dma}</td><td class="score">${r.index}</td><td>${fmt(r.planned)}</td><td>${fmt(r.base)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>openDMA(tr.dataset.dma));drawDMAs();updateDMAKpis($('dmaSelect').value)}
function updateDMAKpis(name){const d=dmas.find(x=>x.dma===name),c=$('category').value;$('kScar').textContent=d?.[c]?.index??'—';const g=geoForDMA(name);if(!g){$('kScore').textContent='—';$('kRR').textContent='—';$('kHH').textContent='—';return}const a=zips.filter(z=>pointInGeom(z,g.geometry)),total=a.reduce((s,z)=>s+(+z.owner_hh||0),0);$('kScore').textContent=a.length?wavgNested(a,'score',c).toFixed(1):'—';$('kRR').textContent=a.length?wavg(a,'replacement_ready').toFixed(1):'—';$('kHH').textContent=a.length?fmt(total):'—'}
function drawDMAs(){layerGroup.clearLayers();$('mapTitle').textContent='DMA Opportunity Map';$('mapSub').textContent=dmaGeo?'Click a DMA on the map or in the rankings to drill into counties and ZIPs.':'Loading DMA boundaries…';if(!dmaGeo)return;const c=$('category').value;L.geoJSON(dmaGeo,{style:f=>{const match=findDMAForFeature(f);const v=match?.[c]?.index||0;return{color:'#fff',weight:1,fillColor:color(Math.min(100,v/1.6)),fillOpacity:v?.65:.08}},onEachFeature:(f,l)=>{const match=findDMAForFeature(f);if(match){const x=match[c];l.bindTooltip(`<b>${match.dma}</b><br>Planned index: ${x.index}<br>Planned HH: ${fmt(x.planned)}`);l.on('click',()=>openDMA(match.dma))}}}).addTo(layerGroup);map.setView([39,-98],4)}
function findDMAForFeature(f){const b=norm(f.properties.NAME);return dmas.find(d=>{const a=aliases[norm(d.dma)]||norm(d.dma);return a===b||b.includes(a)||a.includes(b)})}
function aggregateCounty(arr){const m=new Map,c=$('category').value;for(const z of arr){const key=z.fips;if(!m.has(key))m.set(key,{name:`${z.county}, ${z.state}`,fips:key,zips:[],owner_hh:0});const a=m.get(key);a.zips.push(z);a.owner_hh+=+z.owner_hh||0}return [...m.values()].map(a=>({...a,score:wavgNested(a.zips,'score',c),replacement_ready:wavg(a.zips,'replacement_ready'),need:wavgNested(a.zips,'need',c),lat:avg(a.zips,'lat'),lon:avg(a.zips,'lon')})).sort((a,b)=>b.score-a.score)}
function openDMA(name){$('dmaSelect').value=name;$('view').value='local';toggleControls();selectDMA(name)}
async function selectDMA(name){activeDMA=name;const d=dmas.find(x=>x.dma===name),g=geoForDMA(name);$('kScar').textContent=d?.[$('category').value]?.index||'—';if(!dmaGeo){$('mapSub').textContent='DMA boundaries are still loading. Please select the market again in a moment.';return}if(!g){selectedZips=[];$('kScore').textContent='—';$('kRR').textContent='—';$('kHH').textContent='—';$('mapSub').textContent='DMA boundary match unavailable for this market. ZIP + Radius analysis remains available.';return}$('mapSub').textContent='Calculating counties and ZIPs inside '+name+'…';await new Promise(r=>setTimeout(r,10));selectedZips=zips.filter(z=>pointInGeom(z,g.geometry));renderLocal(name,g)}
function renderLocal(name,g){const c=$('category').value,cs=aggregateCounty(selectedZips);$('mapTitle').textContent=name+' Opportunity';$('countySelect').innerHTML='<option value="all">All counties</option>'+cs.map(x=>`<option value="${x.fips}">${x.name}</option>`).join('');$('countySelect').value='all';$('tableTitle').textContent=name+' — County Rankings';$('tableSub').textContent='Local scores use supplied household/housing ZIP data; Scarborough DMA intent remains context.';$('thead').innerHTML='<tr><th>County</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th></tr>';$('tbody').innerHTML=cs.slice(0,+$('topN').value).map(x=>`<tr data-fips="${x.fips}"><td>${x.name}</td><td class="score">${x.score.toFixed(1)}</td><td>${x.replacement_ready.toFixed(1)}</td><td>${x.need.toFixed(1)}</td><td>${fmt(x.owner_hh)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{$('countySelect').value=tr.dataset.fips;renderZips(tr.dataset.fips)});const all=selectedZips,total=all.reduce((s,z)=>s+(+z.owner_hh||0),0);$('kScore').textContent=all.length?wavgNested(all,'score',c).toFixed(1):'—';$('kRR').textContent=all.length?wavg(all,'replacement_ready').toFixed(1):'—';$('kHH').textContent=all.length?fmt(total):'—';$('mapSub').textContent=`${fmt(all.length)} residential ZIPs across ${fmt(cs.length)} counties. Click a county to see ZIP rankings.`;drawCounties(cs,g)}
function drawCounties(cs,g){layerGroup.clearLayers();L.geoJSON(g,{style:{color:'#17324d',weight:2,fillOpacity:.03}}).addTo(layerGroup);for(const x of cs){L.circleMarker([x.lat,x.lon],{radius:Math.max(5,Math.min(18,4+Math.sqrt(x.owner_hh)/18)),color:'#fff',weight:1,fillColor:color(mapVal(x)),fillOpacity:.85}).bindTooltip(`<b>${x.name}</b><br>Opportunity ${x.score.toFixed(1)}<br>Replacement-Ready ${x.replacement_ready.toFixed(1)}<br>Owner HH ${fmt(x.owner_hh)}`).on('click',()=>{$('countySelect').value=x.fips;renderZips(x.fips)}).addTo(layerGroup)}map.fitBounds(L.geoJSON(g).getBounds(),{padding:[10,10]})}
function renderZips(fips){const c=$('category').value,a=selectedZips.filter(z=>fips==='all'||z.fips===fips).sort((x,y)=>y.score[c]-x.score[c]);$('tableTitle').textContent=(fips==='all'?'ZIP':(a[0]?.county||'')+' ZIP')+' Rankings';$('tableSub').textContent='ZIP opportunity is based on replacement readiness, structural need and addressable owner-household scale.';$('thead').innerHTML='<tr><th>ZIP</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th><th>Older Homes</th><th>Long Residence</th></tr>';$('tbody').innerHTML=a.slice(0,+$('topN').value).map(z=>`<tr><td>${z.zip}</td><td class="score">${z.score[c].toFixed(1)}</td><td>${z.replacement_ready.toFixed(1)}</td><td>${z.need[c].toFixed(1)}</td><td>${fmt(z.owner_hh)}</td><td>${z.old_rate.toFixed(1)}%</td><td>${z.tenure_rate.toFixed(1)}%</td></tr>`).join('');$('mapTitle').textContent=(a[0]?.county?`${a[0].county}, ${a[0].state}`:activeDMA||'ZIP')+' Opportunity';$('mapSub').textContent=`${fmt(a.length)} residential ZIPs shown for the selected geography.`;drawZips(a)}
function drawZips(a){layerGroup.clearLayers();const b=[];for(const z of a.slice(0,1500)){const v=mapVal(z);L.circleMarker([z.lat,z.lon],{radius:5,color:'#fff',weight:.5,fillColor:color(v),fillOpacity:.8}).bindTooltip(`<b>${z.zip}</b><br>Opportunity ${z.score[$('category').value].toFixed(1)}<br>Replacement-Ready ${z.replacement_ready.toFixed(1)}<br>Owner HH ${fmt(z.owner_hh)}`).addTo(layerGroup);b.push([z.lat,z.lon])}if(b.length)map.fitBounds(b,{padding:[15,15]})}
function renderRadius(){const center=zips.find(z=>z.zip===$('centerZip').value);if(!center){$('tableSub').textContent='Enter a valid residential ZIP.';return}const miles=+$('radius').value,a=zips.filter(z=>hav(center,z)<=miles),c=$('category').value;a.sort((x,y)=>y.score[c]-x.score[c]);selectedZips=a;$('tableTitle').textContent=`ZIPs within ${miles} miles of ${center.zip}`;$('tableSub').textContent='All residential ZIPs whose centroids fall within the selected radius.';$('thead').innerHTML='<tr><th>ZIP</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th><th>Miles</th></tr>';$('tbody').innerHTML=a.slice(0,+$('topN').value).map(z=>`<tr><td>${z.zip}</td><td class="score">${z.score[c].toFixed(1)}</td><td>${z.replacement_ready.toFixed(1)}</td><td>${z.need[c].toFixed(1)}</td><td>${fmt(z.owner_hh)}</td><td>${hav(center,z).toFixed(1)}</td></tr>`).join('');$('mapTitle').textContent=`${center.zip} + ${miles} Miles`;$('mapSub').textContent=`${fmt(a.length)} residential ZIPs within the selected radius.`;drawZips(a);$('kScore').textContent=a.length?wavgNested(a,'score',c).toFixed(1):'—';$('kRR').textContent=a.length?wavg(a,'replacement_ready').toFixed(1):'—';$('kHH').textContent=a.length?fmt(a.reduce((s,z)=>s+(+z.owner_hh||0),0)):'—';$('kScar').textContent='—'}
function toggleControls(){const v=$('view').value;$('radiusCtl').classList.toggle('hidden',v!=='radius');$('dmaCtl').classList.toggle('hidden',v==='radius');$('countyCtl').classList.toggle('hidden',v!=='local')}
function viewChange(){toggleControls();const v=$('view').value;if(v==='dma')renderDMA();if(v==='local'&&$('dmaSelect').value)selectDMA($('dmaSelect').value);if(v==='radius'){$('tableTitle').textContent='ZIP + Radius';$('tableSub').textContent='Enter a center ZIP and radius.';$('mapTitle').textContent='ZIP + Radius Opportunity';$('mapSub').textContent='Enter a center ZIP to map nearby residential ZIP opportunity.'}}
async function loadDMAGeo(){const url='https://services.arcgis.com/AgwDJMQH12AGieWa/ArcGIS/rest/services/DMA/FeatureServer/0/query?where=1%3D1&outFields=ID%2CNAME&returnGeometry=true&outSR=4326&f=geojson';try{const r=await fetch(url);if(!r.ok)throw new Error('HTTP '+r.status);dmaGeo=await r.json();if(!dmaGeo?.features?.length)throw new Error('No DMA features returned');if($('view').value==='dma'){drawDMAs();updateDMAKpis($('dmaSelect').value)}else if($('view').value==='local'&&$('dmaSelect').value)selectDMA($('dmaSelect').value)}catch(e){console.warn('DMA map service unavailable',e);$('mapSub').textContent='DMA boundary service is temporarily unavailable. DMA rankings and ZIP + Radius remain available.'}}
async function init(){initMap();toggleControls();try{[zips,dmas]=await Promise.all([fetch('zips.json').then(r=>{if(!r.ok)throw new Error('zips.json');return r.json()}),fetch('dma.json').then(r=>{if(!r.ok)throw new Error('dma.json');return r.json()})]);$('dmaSelect').innerHTML=dmas.map(d=>`<option>${d.dma}</option>`).join('');renderDMA();loadDMAGeo()}catch(e){console.error(e);$('tableSub').textContent='Data files could not be loaded. Confirm zips.json and dma.json are in the same GitHub folder.';return}
$('category').onchange=()=>{if($('view').value==='dma')renderDMA();else if($('view').value==='radius')renderRadius();else selectDMA($('dmaSelect').value)};
$('view').onchange=viewChange;$('dmaSelect').onchange=e=>{if($('view').value==='dma'){updateDMAKpis(e.target.value);drawDMAs()}else openDMA(e.target.value)};$('countySelect').onchange=e=>{if(e.target.value==='all')renderLocal($('dmaSelect').value,geoForDMA($('dmaSelect').value));else renderZips(e.target.value)};
$('topN').onchange=()=>{if($('view').value==='dma')renderDMA();else if($('view').value==='radius')renderRadius();else if($('countySelect').value!=='all')renderZips($('countySelect').value);else renderLocal($('dmaSelect').value,geoForDMA($('dmaSelect').value))};$('centerZip').onchange=renderRadius;$('radius').onchange=renderRadius;$('metric').onchange=()=>{if($('view').value==='dma')drawDMAs();else if($('view').value==='radius')drawZips(selectedZips);else if($('countySelect').value!=='all')renderZips($('countySelect').value);else renderLocal($('dmaSelect').value,geoForDMA($('dmaSelect').value))}}
init();
