let DMA=[],METRO=[],COUNTY=[],ZIP=[];const $=id=>document.getElementById(id);const fmt=n=>Math.round(n||0).toLocaleString();const score=n=>Number(n||0).toFixed(1);
async function init(){[DMA,METRO,COUNTY,ZIP]=await Promise.all(['dma-opportunity','metro-expansion','county-opportunity','zip-opportunity'].map(f=>fetch('data/'+f+'.json').then(r=>r.json())));$('analysis').onchange=setup;$('category').onchange=render;$('market').onchange=marketChanged;$('county').onchange=render;$('radius').onchange=render;setup();}
function mode(){return $('analysis').value}function marketChanged(){if(mode()==='Neighborhood Targeting')setupCounty();else render()}
function setup(){const m=mode(),s=$('market');$('stageNotice').classList.add('hidden');$('view').style.display='block';$('marketWrap').style.display='block';$('countyWrap').style.display='none';$('radiusWrap').style.display='none';
 if(m==='Media Market'){s.innerHTML=DMA.slice().sort((a,b)=>a.dma.localeCompare(b.dma)).map(x=>`<option value="${x.dma_code}">${x.dma}</option>`).join('');if(DMA.some(x=>x.dma_code===751))s.value='751';}
 else{s.innerHTML=METRO.map(x=>`<option value="${x.cbsa}">${x.metro}</option>`).join('');if(METRO.some(x=>x.cbsa==='19740'))s.value='19740';if(m==='Neighborhood Targeting'){ $('countyWrap').style.display='block';$('radiusWrap').style.display='block';setupCounty();return;}}
 render();}
function setupCounty(){const cb=$('market').value,cs=COUNTY.filter(x=>x.cbsa===cb).sort((a,b)=>a.county.localeCompare(b.county));$('county').innerHTML=cs.map(x=>`<option value="${x.fips}">${x.county} County</option>`).join('');if(cb==='19740'&&cs.some(x=>x.fips==='08031'))$('county').value='08031';render();}
function cards(items){$('kpis').innerHTML=items.map(x=>`<div><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}function bars(rows,label,val){$('bars').innerHTML=rows.slice(0,12).map((r,i)=>`<div class="barrow"><span>${i+1}. ${label(r)}</span><div class="track"><div class="fill" style="width:${Math.max(0,Math.min(100,val(r)))}%"></div></div><b>${score(val(r))}</b></div>`).join('')}function metrics(items){$('why').innerHTML=items.map(m=>`<div class="metric"><span>${m[0]}</span><b>${m[1]}</b></div>`).join('')}
function render(){const cat=$('category').value,m=mode();if(m==='Media Market')return renderDMA(cat);if(m==='Market Expansion')return renderMetro(cat);if(m==='Local Opportunity')return renderCounty(cat);return renderZIP(cat)}
function renderDMA(cat){const code=+$('market').value,sorted=DMA.slice().sort((a,b)=>b[cat+'_opportunity']-a[cat+'_opportunity']),x=DMA.find(r=>r.dma_code===code)||sorted[0];updateConditions(cat,'Media Market',x,sorted);cards([['Opportunity Score',score(x[cat+'_opportunity'])],['Replacement Potential',score(x.replacement_ready)],['Service Need',score(x[cat+'_need'])],['Homeowner Scale',score(x.market_scale)],['Category Demand',score(x[cat+'_demand_score'])]]);$('chartTitle').textContent='U.S. Media Market Opportunity';$('chartNote').textContent='Validated Scarborough-based opportunity across 83 matched DMAs.';$('marketName').textContent=x.dma;$('whyTitle').textContent='Why this media market?';metrics([['Replacement Potential',score(x.replacement_ready)],['Service Need',score(x[cat+'_need'])],['Homeowner Scale',score(x.market_scale)],['Category Demand',score(x[cat+'_demand_score'])]]);$('method').textContent='Opportunity = 30% Replacement-Ready Households + 25% Category Demand + 25% Structural Category Need + 20% Market Scale.';bars(sorted,r=>r.dma,r=>r[cat+'_opportunity']);$('tableTitle').textContent='Media Market Rankings';$('thead').innerHTML='<tr><th>Rank</th><th>DMA</th><th>Opportunity</th><th>Owner HH</th><th>ZIPs</th></tr>';$('rankings').innerHTML=sorted.map((r,i)=>`<tr data-code="${r.dma_code}"><td>${i+1}</td><td>${r.dma}</td><td><b>${score(r[cat+'_opportunity'])}</b></td><td>${fmt(r.owner_hh)}</td><td>${r.zip_count}</td></tr>`).join('');rowClicks()}
function renderMetro(cat){const code=$('market').value,sorted=METRO.slice().sort((a,b)=>b[cat]-a[cat]),x=METRO.find(r=>r.cbsa===code)||sorted[0];updateConditions(cat,'Market Expansion',x,sorted);cards([['Expansion Score',score(x[cat])],['Employer Establishments',fmt(x.employer_estab)],['10+ Employee Establishments',fmt(x.estab_10plus)],['50+ Employee Establishments',fmt(x.estab_50plus)],['Contractor Ecosystem',score(x.contractor_ecosystem)]]);$('chartTitle').textContent='U.S. Market Expansion Opportunity';$('chartNote').textContent='387 metropolitan statistical areas only — micropolitan areas are excluded from this view.';$('marketName').textContent=x.metro;$('whyTitle').textContent='Why this expansion market?';metrics([['Category Expansion Score',score(x[cat])],['Employer Establishments',fmt(x.employer_estab)],['10+ Employee Establishments',fmt(x.estab_10plus)],['Contractor Ecosystem',score(x.contractor_ecosystem)]]);$('method').textContent='Market Expansion uses the CBSA employer/contractor model. Scarborough DMA data is not forced into Metro geography.';bars(sorted,r=>r.metro,r=>r[cat]);$('tableTitle').textContent='Metro Rankings — The Operator';$('thead').innerHTML='<tr><th>Rank</th><th>Metro</th><th>Expansion</th><th>Employer Estab.</th><th>10+ Emp.</th><th>50+ Emp.</th></tr>';$('rankings').innerHTML=sorted.map((r,i)=>`<tr data-code="${r.cbsa}"><td>${i+1}</td><td>${r.metro}</td><td><b>${score(r[cat])}</b></td><td>${fmt(r.employer_estab)}</td><td>${fmt(r.estab_10plus)}</td><td>${fmt(r.estab_50plus)}</td></tr>`).join('');rowClicks()}
function renderCounty(cat){const code=$('market').value,sorted=COUNTY.filter(r=>r.cbsa===code).sort((a,b)=>b[cat+'_score']-a[cat+'_score']),x=sorted[0],metro=METRO.find(r=>r.cbsa===code);if(!x)return;updateConditions(cat,'Local Opportunity',x,sorted);cards([['Top County Score',score(x[cat+'_score'])],['Replacement-Ready HH',fmt(x.replacement_ready_hh)],['Owner Households',fmt(x.owner_hh)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)]]);$('chartTitle').textContent=(metro?metro.metro:'Selected Metro')+' — County Opportunity';$('chartNote').textContent='Counties are ranked only within the selected Metro. Scores are rebuilt from residential ZIP housing inputs.';$('marketName').textContent=x.county+' County';$('whyTitle').textContent='Top local opportunity';metrics([['Replacement Potential',score(x.replacement_ready)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)],['Residential ZIPs',x.zip_count]]);$('method').textContent='Local Opportunity = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale. DMA Scarborough is not represented as county-level measurement.';bars(sorted,r=>r.county,r=>r[cat+'_score']);$('tableTitle').textContent='County Rankings — The Branch';$('thead').innerHTML='<tr><th>Rank</th><th>County</th><th>Opportunity</th><th>Replacement-Ready HH</th><th>Owner HH</th><th>ZIPs</th></tr>';$('rankings').innerHTML=sorted.map((r,i)=>`<tr><td>${i+1}</td><td>${r.county}</td><td><b>${score(r[cat+'_score'])}</b></td><td>${fmt(r.replacement_ready_hh)}</td><td>${fmt(r.owner_hh)}</td><td>${r.zip_count}</td></tr>`).join('')}
function miles(a,b,c,d){const R=3958.8,p=Math.PI/180,x=(c-a)*p,y=(d-b)*p,q=Math.sin(x/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function renderZIP(cat){const cb=$('market').value,fips=$('county').value,rad=+$('radius').value;let base=ZIP.filter(r=>r.cbsa===cb&&r.fips===fips),rows=base;if(rad>0&&base.length){const center=base.slice().sort((a,b)=>b.households-a.households)[0];rows=ZIP.filter(r=>r.cbsa===cb&&miles(center.lat,center.lon,r.lat,r.lon)<=rad)}const sorted=rows.slice().sort((a,b)=>b[cat+'_score']-a[cat+'_score']),x=sorted[0],metro=METRO.find(r=>r.cbsa===cb);if(!x)return;updateConditions(cat,'Neighborhood Targeting',x,sorted);cards([['Top ZIP Score',score(x[cat+'_score'])],['Replacement-Ready HH',fmt(x.replacement_ready_hh)],['Owner Households',fmt(x.owner_hh)],['Structural Need',score(x[cat+'_need'])],['ZIPs in View',sorted.length]]);$('chartTitle').textContent=(metro?metro.metro:'Selected Metro')+' — Neighborhood Targeting';$('chartNote').textContent=rad?`Residential ZIPs within ${rad} miles of the selected county's household center ZIP.`:'Residential ZIPs in the selected county.';$('marketName').textContent='ZIP '+x.zip+' · '+x.county+' County';$('whyTitle').textContent='Top neighborhood opportunity';metrics([['Replacement Potential',score(x.replacement_ready)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)],['Owner Rate',score(x.owner_rate)+'%'],['Single-Family Rate',score(x.sf_rate)+'%']]);$('method').textContent='ZIP Opportunity = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale. No Scarborough propensity is represented as ZIP-level measurement.';bars(sorted,r=>'ZIP '+r.zip,r=>r[cat+'_score']);$('tableTitle').textContent='ZIP Rankings — The Local Pro';$('thead').innerHTML='<tr><th>Rank</th><th>ZIP</th><th>County</th><th>Opportunity</th><th>Replacement-Ready HH</th><th>Owner HH</th><th>Owner %</th><th>SF %</th></tr>';$('rankings').innerHTML=sorted.map((r,i)=>`<tr><td>${i+1}</td><td>${r.zip}</td><td>${r.county}</td><td><b>${score(r[cat+'_score'])}</b></td><td>${fmt(r.replacement_ready_hh)}</td><td>${fmt(r.owner_hh)}</td><td>${score(r.owner_rate)}%</td><td>${score(r.sf_rate)}%</td></tr>`).join('')}
function rowClicks(){document.querySelectorAll('#rankings tr[data-code]').forEach(tr=>tr.onclick=()=>{$('market').value=tr.dataset.code;if(mode()==='Neighborhood Targeting')setupCounty();else render();window.scrollTo({top:0,behavior:'smooth'})})}init();

// Market Conditions layer: descriptive statistics are intentionally separate from scoring.
const INDUSTRY={
 hvac:{title:'HVAC industry pulse',text:"AHRI's July 2026 U.S. heating and cooling equipment shipment release provides the latest national manufacturer-shipment context. It is national context, not a local demand estimate.",source:'AHRI · July 2026 U.S. Heating and Cooling Equipment Shipments'},
 roofing:{title:'Home improvement & repair pulse',text:'Harvard JCHS projects owner-occupied home improvement and repair spending of about $519B through mid-2027, with year-over-year growth slowing to 0.5% by 2027 Q2.',source:'Harvard Joint Center for Housing Studies · LIRA · July 23, 2026'},
 windows:{title:'Home improvement & repair pulse',text:'Harvard JCHS projects owner-occupied home improvement and repair spending of about $519B through mid-2027, with year-over-year growth slowing to 0.5% by 2027 Q2.',source:'Harvard Joint Center for Housing Studies · LIRA · July 23, 2026'}
};
function pct(n){return Number(n||0).toFixed(1)+'%'}
function money(n){return n?('$'+Math.round(n).toLocaleString()):'—'}
function weighted(rows,key,weight='households'){const den=rows.reduce((s,r)=>s+(+r[weight]||0),0);return den?rows.reduce((s,r)=>s+(+r[key]||0)*(+r[weight]||0),0)/den:0}
function conditionCards(items,cat){$('conditions').innerHTML=items.map(x=>`<div class="condition-card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');const i=INDUSTRY[cat];$('industry').innerHTML=`<strong>${i.title}</strong>${i.text}<div class="source-note">Source: ${i.source}. Local housing statistics come from the analyzer's validated housing/ZIP source layer. These statistics do not alter the Opportunity Score.</div>`}
function updateConditions(cat,m,x,rows){let items=[];
 if(m==='Media Market'){items=[['Households',fmt(x.households)],['Owner households',fmt(x.owner_hh)],['Homeownership',pct(100*x.owner_hh/Math.max(1,x.households))],['Residential ZIPs',fmt(x.zip_count)],['Category demand index',score(x[cat+'_demand_index'])]];}
 else if(m==='Market Expansion'){const z=ZIP.filter(r=>r.cbsa===x.cbsa);items=[['Households',fmt(z.reduce((s,r)=>s+r.households,0))],['Owner households',fmt(z.reduce((s,r)=>s+r.owner_hh,0))],['Homeownership',pct(weighted(z,'owner_rate'))],['Single-family homes',pct(weighted(z,'sf_rate'))],['Older housing stock',pct(weighted(z,'old_rate'))],['Median HH income',money(weighted(z,'income'))]];}
 else if(m==='Local Opportunity'){const z=ZIP.filter(r=>r.fips===x.fips);items=[['Households',fmt(x.households)],['Owner households',fmt(x.owner_hh)],['Homeownership',pct(weighted(z,'owner_rate'))],['Single-family homes',pct(weighted(z,'sf_rate'))],['Older housing stock',pct(weighted(z,'old_rate'))],['Long-tenure households',pct(weighted(z,'tenure_rate'))]];}
 else {items=[['Households',fmt(x.households)],['Owner households',fmt(x.owner_hh)],['Homeownership',pct(x.owner_rate)],['Single-family homes',pct(x.sf_rate)],['Older housing stock',pct(x.old_rate)],['Long-tenure households',pct(x.tenure_rate)],['Median HH income',money(x.income)],['Median home value',money(x.home_value)]];}
 conditionCards(items,cat);
}

const METHOD={
 'Media Market':{label:'DMA — The Ad Shop',purpose:'Media-market demand and propensity. This layer answers where category demand and replacement-ready homeowner opportunity are strongest at the DMA level.',formula:'Opportunity Score = 30% Replacement-Ready Households + 25% Category Demand + 25% Structural Category Need + 20% Market Scale.',data:'Scarborough category-demand measures are reconciled to validated DMAs and combined with the analyzer housing/household source layer.',caution:'DMA scores are relative 0–100 opportunity measures. Scarborough DMA observations are not represented as Metro, County or ZIP measurements.'},
 'Market Expansion':{label:'Metro — The Operator',purpose:'Business/market expansion opportunity. This layer answers which metropolitan areas have the strongest contractor/employer ecosystem for category expansion.',formula:'Expansion Score uses the validated CBSA employer/contractor model, including employer establishments, larger establishments and contractor ecosystem measures.',data:'CBSA is the authoritative market identifier. The view is restricted to metropolitan statistical areas; micropolitan areas are excluded.',caution:'Scarborough DMA data is not forced into Metro geography. Market Conditions are descriptive and do not alter the Expansion Score.'},
 'Local Opportunity':{label:'County — The Branch',purpose:'Local branch opportunity inside the selected Metro. This layer identifies where replacement-ready households and structural service need are concentrated.',formula:'Local Opportunity Score = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale.',data:'County values are rebuilt from the validated residential ZIP housing layer for counties belonging to the selected Metro.',caution:'DMA Scarborough propensity may provide market context, but it is not represented as county-level measurement. Scores rank counties within the selected Metro.'},
 'Neighborhood Targeting':{label:'ZIP — The Local Pro',purpose:'Neighborhood targeting and service-area prioritization. This layer identifies residential ZIPs with the strongest local opportunity.',formula:'ZIP Opportunity Score = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale.',data:'Residential ZIP inputs include homeownership, single-family concentration, housing age, residence tenure, household economics and addressable household scale. Radius views include qualifying residential ZIPs around the selected county center ZIP.',caution:'No Scarborough propensity is represented as ZIP-level measurement. ZIP scores are relative opportunity measures, not forecasts of leads, sales, revenue or market share.'}
};
function methodologyHTML(){const x=METHOD[mode()];return `<p><b>${x.label}</b></p><div class="method-section"><h3>What this layer answers</h3><p>${x.purpose}</p></div><div class="method-section"><h3>Score construction</h3><div class="method-formula">${x.formula}</div></div><div class="method-section"><h3>Data treatment</h3><p>${x.data}</p></div><div class="method-section"><h3>How to read Market Conditions</h3><p><b>Opportunity Score</b> determines ranking. <b>Market Conditions</b> are reported/observed statistics that help explain the selected geography. <b>Industry Pulse</b> provides broader category context. Market Conditions and Industry Pulse do not change the score unless explicitly identified as score inputs.</p></div><div class="method-section"><h3>Interpretation</h3><div class="method-caution">${x.caution} All 0–100 scores are relative measures for prioritization and are not forecasts of leads, sales, revenue or market share.</div></div>`}
function openMethod(){ $('methodModalTitle').textContent='Methodology · '+METHOD[mode()].label; $('methodBody').innerHTML=methodologyHTML(); $('methodModal').classList.remove('hidden') }
function csvEscape(v){v=String(v??'');return /[",\n]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function exportCSV(){const table=document.querySelector('table'),rows=[...table.querySelectorAll('tr')].map(tr=>[...tr.children].map(td=>csvEscape(td.innerText.trim())).join(','));const blob=new Blob([rows.join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='home-services-'+mode().toLowerCase().replace(/\s+/g,'-')+'-'+$('category').value+'-rankings.csv';a.click();URL.revokeObjectURL(a.href)}
window.addEventListener('DOMContentLoaded',()=>{$('methodBtn').onclick=openMethod;$('methodClose').onclick=()=> $('methodModal').classList.add('hidden');$('methodModal').onclick=e=>{if(e.target===$('methodModal'))$('methodModal').classList.add('hidden')};$('csvBtn').onclick=exportCSV});

// Production controls and geographic QA enhancements.
function rankRows(rows,key){const dir=$('rankDir')?.value||'top';return rows.slice().sort((a,b)=>dir==='bottom'?(a[key]-b[key]):(b[key]-a[key]))}
function visibleRows(rows){return rows.slice(0,+($('topN')?.value||25))}
function safeCenterZip(){return String($('centerZip')?.value||'').replace(/\D/g,'').slice(0,5)}
function zipRecord(z){return ZIP.find(r=>r.zip===z)}
function centroidFor(rows){const ok=rows.filter(r=>Number.isFinite(+r.lat)&&Number.isFinite(+r.lon));if(!ok.length)return null;const w=ok.reduce((s,r)=>s+(+r.households||1),0);return {lat:ok.reduce((s,r)=>s+(+r.lat)*(+r.households||1),0)/w,lon:ok.reduce((s,r)=>s+(+r.lon)*(+r.households||1),0)/w}}
function renderGeoMap(rows,labelFn,scoreFn,selectedLabel){const el=$('map');if(!el)return;let pts=[];for(const r of visibleRows(rows)){let c;if(r.lat!=null)c={lat:+r.lat,lon:+r.lon};else if(r.fips)c=centroidFor(ZIP.filter(z=>z.fips===r.fips));else if(r.cbsa)c=centroidFor(ZIP.filter(z=>z.cbsa===r.cbsa));else if(r.dma_code)c=centroidFor(ZIP.filter(z=>String(z.dma_code)===String(r.dma_code)));if(c&&Number.isFinite(c.lat)&&Number.isFinite(c.lon))pts.push({...c,label:labelFn(r),score:+scoreFn(r),selected:labelFn(r)===selectedLabel})}
 if(!pts.length){el.innerHTML='<div style="padding:20px;color:#68767e">Geographic coordinates are not available for this view.</div>';return}
 const minLat=Math.min(...pts.map(p=>p.lat)),maxLat=Math.max(...pts.map(p=>p.lat)),minLon=Math.min(...pts.map(p=>p.lon)),maxLon=Math.max(...pts.map(p=>p.lon));const W=900,H=340,pad=24;const dx=Math.max(.01,maxLon-minLon),dy=Math.max(.01,maxLat-minLat);const dots=pts.map(p=>{const x=pad+(p.lon-minLon)/dx*(W-2*pad),y=H-pad-(p.lat-minLat)/dy*(H-2*pad),rr=5+Math.max(0,Math.min(100,p.score))/18;return `<circle class="map-dot${p.selected?' selected':''}" cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${rr.toFixed(1)}"><title>${p.label}: ${score(p.score)}</title></circle>`}).join('');el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Relative geographic opportunity positions">${dots}</svg><div class="legend">Dot size = opportunity score · hover for value</div>`}
function rowsToTable(rows,html){return visibleRows(rows).map(html).join('')}

// Override setup to support independent service-area radius.
function setup(){const m=mode(),s=$('market');$('stageNotice').classList.add('hidden');$('view').style.display='block';$('marketWrap').style.display='block';$('countyWrap').style.display='none';$('radiusWrap').style.display='none';if($('centerZipWrap'))$('centerZipWrap').style.display='none';
 if(m==='Media Market'){s.innerHTML=DMA.slice().sort((a,b)=>a.dma.localeCompare(b.dma)).map(x=>`<option value="${x.dma_code}">${x.dma}</option>`).join('');if(DMA.some(x=>x.dma_code===751))s.value='751';}
 else{s.innerHTML=METRO.slice().sort((a,b)=>a.metro.localeCompare(b.metro)).map(x=>`<option value="${x.cbsa}">${x.metro}</option>`).join('');if(METRO.some(x=>x.cbsa==='19740'))s.value='19740';if(m==='Neighborhood Targeting'){$('countyWrap').style.display='block';$('radiusWrap').style.display='block';if($('centerZipWrap'))$('centerZipWrap').style.display='block';setupCounty();return;}}
 render()}
function setupCounty(){const cb=$('market').value,cs=COUNTY.filter(x=>x.cbsa===cb).sort((a,b)=>a.county.localeCompare(b.county));$('county').innerHTML=cs.map(x=>`<option value="${x.fips}">${x.county} County</option>`).join('');if(cb==='19740'&&cs.some(x=>x.fips==='08031'))$('county').value='08031';const base=ZIP.filter(r=>r.cbsa===cb&&r.fips===$('county').value).sort((a,b)=>b.households-a.households);if($('centerZip')&&!safeCenterZip()&&base[0])$('centerZip').value=base[0].zip;render()}
function marketChanged(){if(mode()==='Neighborhood Targeting')setupCounty();else render()}

function renderDMA(cat){const code=+$('market').value,key=cat+'_opportunity',sorted=rankRows(DMA,key),x=DMA.find(r=>r.dma_code===code)||sorted[0];updateConditions(cat,'Media Market',x,sorted);cards([['Opportunity Score',score(x[key])],['Replacement Potential',score(x.replacement_ready)],['Service Need',score(x[cat+'_need'])],['Homeowner Scale',score(x.market_scale)],['Category Demand',score(x[cat+'_demand_score'])]]);$('chartTitle').textContent='U.S. Media Market Opportunity';$('chartNote').textContent='Validated Scarborough-based opportunity across 83 matched DMAs.';$('marketName').textContent=x.dma;$('whyTitle').textContent='Why this media market?';metrics([['Replacement Potential',score(x.replacement_ready)],['Service Need',score(x[cat+'_need'])],['Homeowner Scale',score(x.market_scale)],['Category Demand',score(x[cat+'_demand_score'])]]);$('method').textContent='Opportunity = 30% Replacement-Ready Households + 25% Category Demand + 25% Structural Category Need + 20% Market Scale.';bars(visibleRows(sorted),r=>r.dma,r=>r[key]);renderGeoMap(sorted,r=>r.dma,r=>r[key],x.dma);$('mapNote').textContent='Relative positions of the displayed DMA opportunity centroids.';$('tableTitle').textContent='Media Market Rankings — The Ad Shop';$('thead').innerHTML='<tr><th>Rank</th><th>DMA</th><th>Opportunity</th><th>Owner HH</th><th>ZIPs</th></tr>';$('rankings').innerHTML=rowsToTable(sorted,(r,i)=>`<tr data-code="${r.dma_code}"><td>${i+1}</td><td>${r.dma}</td><td><b>${score(r[key])}</b></td><td>${fmt(r.owner_hh)}</td><td>${r.zip_count}</td></tr>`);rowClicks()}
function renderMetro(cat){const code=$('market').value,key=cat,sorted=rankRows(METRO,key),x=METRO.find(r=>r.cbsa===code)||sorted[0];updateConditions(cat,'Market Expansion',x,sorted);cards([['Expansion Score',score(x[key])],['Employer Establishments',fmt(x.employer_estab)],['10+ Employee Establishments',fmt(x.estab_10plus)],['50+ Employee Establishments',fmt(x.estab_50plus)],['Contractor Ecosystem',score(x.contractor_ecosystem)]]);$('chartTitle').textContent='U.S. Market Expansion Opportunity';$('chartNote').textContent='387 metropolitan statistical areas only — micropolitan areas are excluded.';$('marketName').textContent=x.metro;$('whyTitle').textContent='Why this expansion market?';metrics([['Category Expansion Score',score(x[key])],['Employer Establishments',fmt(x.employer_estab)],['10+ Employee Establishments',fmt(x.estab_10plus)],['Contractor Ecosystem',score(x.contractor_ecosystem)]]);$('method').textContent='Market Expansion uses the CBSA employer/contractor model. Scarborough DMA data is not forced into Metro geography.';bars(visibleRows(sorted),r=>r.metro,r=>r[key]);renderGeoMap(sorted,r=>r.metro,r=>r[key],x.metro);$('mapNote').textContent='Relative positions of the displayed metropolitan opportunity centroids.';$('tableTitle').textContent='Metro Rankings — The Operator';$('thead').innerHTML='<tr><th>Rank</th><th>Metro</th><th>Expansion</th><th>Employer Estab.</th><th>10+ Emp.</th><th>50+ Emp.</th></tr>';$('rankings').innerHTML=rowsToTable(sorted,(r,i)=>`<tr data-code="${r.cbsa}"><td>${i+1}</td><td>${r.metro}</td><td><b>${score(r[key])}</b></td><td>${fmt(r.employer_estab)}</td><td>${fmt(r.estab_10plus)}</td><td>${fmt(r.estab_50plus)}</td></tr>`);rowClicks()}
function renderCounty(cat){const code=$('market').value,key=cat+'_score',sorted=rankRows(COUNTY.filter(r=>r.cbsa===code),key),x=sorted[0],metro=METRO.find(r=>r.cbsa===code);if(!x)return;updateConditions(cat,'Local Opportunity',x,sorted);cards([['Top County Score',score(x[key])],['Replacement-Ready HH',fmt(x.replacement_ready_hh)],['Owner Households',fmt(x.owner_hh)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)]]);$('chartTitle').textContent=(metro?metro.metro:'Selected Metro')+' — County Opportunity';$('chartNote').textContent='Counties are ranked within the selected Metro from residential ZIP housing inputs.';$('marketName').textContent=x.county+' County';$('whyTitle').textContent='Leading local opportunity in this view';metrics([['Replacement Potential',score(x.replacement_ready)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)],['Residential ZIPs',x.zip_count]]);$('method').textContent='Local Opportunity = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale.';bars(visibleRows(sorted),r=>r.county,r=>r[key]);renderGeoMap(sorted,r=>r.county+' County',r=>r[key],x.county+' County');$('mapNote').textContent='Relative positions of county residential centroids within the selected Metro.';$('tableTitle').textContent='County Rankings — The Branch';$('thead').innerHTML='<tr><th>Rank</th><th>County</th><th>Opportunity</th><th>Replacement-Ready HH</th><th>Owner HH</th><th>ZIPs</th></tr>';$('rankings').innerHTML=rowsToTable(sorted,(r,i)=>`<tr><td>${i+1}</td><td>${r.county}</td><td><b>${score(r[key])}</b></td><td>${fmt(r.replacement_ready_hh)}</td><td>${fmt(r.owner_hh)}</td><td>${r.zip_count}</td></tr>`)}
function renderZIP(cat){const cb=$('market').value,fips=$('county').value,rad=+$('radius').value,key=cat+'_score';let rows,center=null,centerZip=safeCenterZip();if(rad>0){center=zipRecord(centerZip);if(!center){const fallback=ZIP.filter(r=>r.cbsa===cb&&r.fips===fips).sort((a,b)=>b.households-a.households)[0];center=fallback;if(center&&$('centerZip'))$('centerZip').value=center.zip}rows=center?ZIP.filter(r=>miles(center.lat,center.lon,r.lat,r.lon)<=rad):[]}else rows=ZIP.filter(r=>r.cbsa===cb&&r.fips===fips);const sorted=rankRows(rows,key),x=sorted[0],metro=METRO.find(r=>r.cbsa===cb);if(!x){$('rankings').innerHTML='';return}updateConditions(cat,'Neighborhood Targeting',x,sorted);cards([['Leading ZIP Score',score(x[key])],['Replacement-Ready HH',fmt(x.replacement_ready_hh)],['Owner Households',fmt(x.owner_hh)],['Structural Need',score(x[cat+'_need'])],['ZIPs in View',sorted.length]]);$('chartTitle').textContent=rad?`Service Area · ZIP ${center.zip} · ${rad} miles`:(metro?metro.metro:'Selected Metro')+' — Neighborhood Targeting';$('chartNote').textContent=rad?`All residential ZIPs whose centroids fall within ${rad} straight-line miles of ZIP ${center.zip}; County, Metro and DMA boundaries do not constrain the service area.`:'Residential ZIPs in the selected county.';$('marketName').textContent='ZIP '+x.zip+' · '+x.county+' County';$('whyTitle').textContent='Leading neighborhood opportunity in this view';metrics([['Replacement Potential',score(x.replacement_ready)],['Structural Need',score(x[cat+'_need'])],['Addressable Scale',score(x.addressable_scale)],['Owner Rate',score(x.owner_rate)+'%'],['Single-Family Rate',score(x.sf_rate)+'%']]);$('method').textContent='ZIP Opportunity = 40% Replacement-Ready Households + 35% Structural Category Need + 25% Addressable Scale. Radius uses great-circle distance between ZIP centroids and can cross County, Metro and DMA boundaries.';bars(visibleRows(sorted),r=>'ZIP '+r.zip,r=>r[key]);renderGeoMap(sorted,r=>'ZIP '+r.zip,r=>r[key],'ZIP '+x.zip);$('mapNote').textContent=rad?`Residential ZIP centroids within ${rad} miles of ZIP ${center.zip}.`:'Residential ZIP centroids in the selected county.';$('tableTitle').textContent='ZIP Rankings — The Local Pro';$('thead').innerHTML='<tr><th>Rank</th><th>ZIP</th><th>County</th><th>Metro</th><th>Opportunity</th><th>Replacement-Ready HH</th><th>Owner HH</th><th>Owner %</th><th>SF %</th></tr>';$('rankings').innerHTML=rowsToTable(sorted,(r,i)=>`<tr><td>${i+1}</td><td>${r.zip}</td><td>${r.county}</td><td>${r.metro||'—'}</td><td><b>${score(r[key])}</b></td><td>${fmt(r.replacement_ready_hh)}</td><td>${fmt(r.owner_hh)}</td><td>${score(r.owner_rate)}%</td><td>${score(r.sf_rate)}%</td></tr>`)}

// Replace the earlier ZIP methodology text with the locked independent service-area definition.
METHOD['Neighborhood Targeting'].data='Residential ZIP inputs include homeownership, single-family concentration, housing age, residence tenure, household economics and addressable household scale. Service Area Radius starts from the user-entered center ZIP and includes all residential ZIP centroids within the selected straight-line distance, regardless of County, Metro or DMA boundaries.';
METHOD['Neighborhood Targeting'].caution='No Scarborough propensity is represented as ZIP-level measurement. Radius uses ZIP centroid coordinates for targeting; Census ZCTA polygons, when used for display, are statistical approximations and not USPS delivery boundaries.';

window.addEventListener('DOMContentLoaded',()=>{if($('rankDir'))$('rankDir').onchange=render;if($('topN'))$('topN').onchange=render;if($('centerZip')){$('centerZip').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,5);$('centerZip').onchange=()=>{if(+$('radius').value>0)render()}};$('county').onchange=()=>{if(mode()==='Neighborhood Targeting'){const base=ZIP.filter(r=>r.cbsa===$('market').value&&r.fips===$('county').value).sort((a,b)=>b.households-a.households);if(base[0]&&+$('radius').value===0)$('centerZip').value=base[0].zip}render()};$('radius').onchange=render});
