const $=id=>document.getElementById(id);let zips=[],dmas=[],metroMap={},metros=[],dmaGeo=null,map,layerGroup,currentZips=[],forecastMap=null,forecastOverlay=null;const dmaZipCache=new Map();
const catLabel={hvac:'HVAC',roofing:'Roofing',windows:'Windows & Doors'};
function zip5(v){let s=String(v??'').trim();return /^\d{1,5}$/.test(s)?s.padStart(5,'0'):s}function norm(s){return(s||'').toLowerCase().replace(/dma/g,'').replace(/fort /g,'ft ').replace(/saint /g,'st ').replace(/[^a-z0-9]/g,'')}
const aliases={
'miamiftlauderdale':'miamiftlauderdale',
'tampastpetersburg':'tampastpetesarasota',
'tampastpetersburgclearwater':'tampastpetesarasota',
'orlandodaytonabeachmelbourne':'orlandodaytonabchmelbrn',
'hartfordnewhaven':'hartfordnewhaven',
'hartfordnewbritainmiddletown':'hartfordnewhaven',
'washingtondc':'washingtondchagrstwn',
'clevelandakron':'clevelandakroncanton',
'wilkesbarrescranton':'wilkesbarrescrantonhztn',
'denverboulder':'denver',
'denver':'denver',
'dallasftworth':'dallasftworth',
'dallasfortworth':'dallasftworth',
'minneapolisstpaul':'minneapolisstpaul',
'seattletacoma':'seattletacoma',
'greensborowinstonsalemhighpoint':'greensborohpointwsalem',
'greenvillespartanburg':'greenvillespartanburgashevilleanderson',
'raleighdurham':'raleighdurhamfayetteville',
'saltlakecityogdenprovo':'saltlakecity',
'mcallenbrownsvilleharlingen':'harlingenweslacobrownsvillemcallen',
'norfolkvirginiabeachnewportnews':'norfolkportsmouthnewportnews',
'providencewarwickpawtucket':'providencenewbedford',
'roanokelynchburg':'roanokelynchburg',
'fortmyersnaples':'ftmyersnaples',
'fortpiercestuartverobeach':'westpalmbeachftpierce',
'westpalmbeachbocaraton':'westpalmbeachftpierce'
};
function fmt(n){return Math.round(n||0).toLocaleString()}function avg(a,k){return a.length?a.reduce((s,x)=>s+(+x[k]||0),0)/a.length:0}function wavg(a,k){let d=a.reduce((s,x)=>s+(+x.owner_hh||0),0);return d?a.reduce((s,x)=>s+(+x[k]||0)*(+x.owner_hh||0),0)/d:0}function wavgN(a,o,k){let d=a.reduce((s,x)=>s+(+x.owner_hh||0),0);return d?a.reduce((s,x)=>s+(+x[o]?.[k]||0)*(+x.owner_hh||0),0)/d:0}
function hav(a,b){const R=3958.8,r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlon=r(b.lon-a.lon),q=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
function pointInRing(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){let xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];if(((yi>y)!=(yj>y))&&(x<(xj-xi)*(y-yi)/(yj-yi+1e-12)+xi))inside=!inside}return inside}function pointInGeom(z,g){const ps=g.type==='Polygon'?[g.coordinates]:g.coordinates;return ps.some(p=>pointInRing(z.lon,z.lat,p[0]))}
function dmaFeatureName(f){return f?.properties?.dma1||f?.properties?.NAME||f?.properties?.name||''}
function geoForDMA(name){if(!dmaGeo)return null;let n=aliases[norm(name)]||norm(name);return dmaGeo.features.find(f=>norm(dmaFeatureName(f))===n)||dmaGeo.features.find(f=>{let x=norm(dmaFeatureName(f));return x.includes(n)||n.includes(x)})}
function color(v){return v>=75?'#17324d':v>=60?'#315c7d':v>=45?'#6f91aa':v>=30?'#a8bbc8':'#d9e2e7'}function mapVal(x){let c=$('category').value;return x.score?.[c]??x.score??0}
function initMap(){map=L.map('map').setView([39,-98],4);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);layerGroup=L.layerGroup().addTo(map)}
function attachMetro(){for(const z of zips){z.zip=zip5(z.zip);z.fips=String(z.fips??'').padStart(5,'0');z.metro=metroMap[z.zip]?.metro||metroMap[String(+z.zip)]?.metro||'';}let m=new Map;for(const z of zips){if(!z.metro)continue;if(!m.has(z.metro))m.set(z.metro,[]);m.get(z.metro).push(z)}metros=[...m].map(([name,a])=>aggregate(name,a)).sort((a,b)=>b.score[$('category')?.value||'hvac']-a.score[$('category')?.value||'hvac'])}
function aggregate(name,a){return{name,zips:a,owner_hh:a.reduce((s,z)=>s+z.owner_hh,0),replacement_ready:wavg(a,'replacement_ready'),need:{hvac:wavgN(a,'need','hvac'),roofing:wavgN(a,'need','roofing'),windows:wavgN(a,'need','windows')},score:{hvac:wavgN(a,'score','hvac'),roofing:wavgN(a,'score','roofing'),windows:wavgN(a,'score','windows')},lat:avg(a,'lat'),lon:avg(a,'lon')}}
function counties(a){let m=new Map;for(const z of a){let k=z.fips;if(!m.has(k))m.set(k,{fips:k,name:`${z.county}, ${z.state}`,zips:[]});m.get(k).zips.push(z)}return[...m.values()].map(x=>({...aggregate(x.name,x.zips),fips:x.fips})).sort((a,b)=>b.score[$('category').value]-a.score[$('category').value])}
function setKpis(a,scar='—'){let c=$('category').value;if(!a.length){$('kScore').textContent=$('kRR').textContent=$('kHH').textContent='—'}else{$('kScore').textContent=wavgN(a,'score',c).toFixed(1);$('kRR').textContent=wavg(a,'replacement_ready').toFixed(1);$('kHH').textContent=fmt(a.reduce((s,z)=>s+z.owner_hh,0))}$('kScar').textContent=scar}
function populateMarkets(){let g=$('geo').value,p=$('parentType').value,c=$('category').value,opts=[];if(g==='dma'||(g!=='metro'&&p==='dma'))opts=dmas.map(d=>d.dma);else opts=metros.slice().sort((a,b)=>b.score[c]-a.score[c]).map(m=>m.name);$('marketLabel').textContent=(g==='dma'||(g!=='metro'&&p==='dma'))?'DMA':'Metro';$('marketSelect').innerHTML=opts.map(x=>`<option>${x}</option>`).join('');}
function renderDMA(){let c=$('category').value,rows=dmas.map(d=>({...d,index:d[c]?.index||0,planned:d[c]?.planned||0,base:d[c]?.base||0})).sort((a,b)=>b.index-a.index);$('tableTitle').textContent='U.S. Media Market Rankings';$('tableSub').textContent='National DMA comparison. Click a market to inspect its opportunity drivers.';$('thead').innerHTML='<tr><th>DMA</th><th>Intent Index</th><th>Planned HH</th><th>Base HH</th></tr>';$('tbody').innerHTML=rows.slice(0,+$('topN').value).map(r=>`<tr data-name="${r.dma}"><td>${r.dma}</td><td class="score">${r.index}</td><td>${fmt(r.planned)}</td><td>${fmt(r.base)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{renderDMASelection(tr.dataset.name)});drawDMAs();$('kScore').textContent=$('kRR').textContent=$('kHH').textContent='—';$('kScar').textContent='—'}
function drawDMAs(){layerGroup.clearLayers();if(!dmaGeo)return;let c=$('category').value,lookup=new Map(dmas.map(d=>[norm(d.dma),d[c]?.index||0]));L.geoJSON(dmaGeo,{style:f=>{let v=lookup.get(norm(dmaFeatureName(f)))||0;return{color:'#fff',weight:1,fillColor:color(Math.min(100,v/1.6)),fillOpacity:v?.65:.08}},onEachFeature:(f,l)=>{let match=dmas.find(d=>{let a=aliases[norm(d.dma)]||norm(d.dma),b=norm(dmaFeatureName(f));return a===b||b.includes(a)||a.includes(b)});if(match){let x=match[c];l.bindTooltip(`<b>${match.dma}</b><br>Scarborough intent: ${x.index}`);l.on('click',()=>{renderDMASelection(match.dma)})}}}).addTo(layerGroup);map.setView([39,-98],4)}
async function dmaZips(name){if(dmaZipCache.has(name))return dmaZipCache.get(name);let g=geoForDMA(name);if(!g){console.warn('No DMA boundary match for',name);return[];}await new Promise(r=>setTimeout(r,0));let a=zips.filter(z=>pointInGeom(z,g.geometry));dmaZipCache.set(name,a);return a}
async function renderDMASelection(name){let d=dmas.find(x=>x.dma===name),a=await dmaZips(name),c=$('category').value;currentZips=a;setKpis(a,d?.[c]?.index||'—');$('mapTitle').textContent=name+' Opportunity';$('mapSub').textContent=`${fmt(a.length)} residential ZIPs in mapped DMA boundary.`;drawPoints(a);if(a.length){$('whySub').textContent=`${name} · ${catLabel[c]}`;$('whyRR').textContent=wavg(a,'replacement_ready').toFixed(1);$('whyNeed').textContent=wavgN(a,'need',c).toFixed(1);$('whyScale').textContent=fmt(a.reduce((s,z)=>s+z.owner_hh,0));$('whyDemand').textContent=d?.[c]?.index||'—';}}
function renderMetroList(){let c=$('category').value,rows=metros.slice().sort((a,b)=>b.score[c]-a.score[c]);$('tableTitle').textContent='Market Expansion Rankings';$('tableSub').textContent='CBSA/metro opportunity aggregated from supplied residential ZIP housing data.';$('thead').innerHTML='<tr><th>Metro</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th></tr>';$('tbody').innerHTML=rows.slice(0,+$('topN').value).map(r=>`<tr data-name="${r.name}"><td>${r.name}</td><td class="score">${r.score[c].toFixed(1)}</td><td>${r.replacement_ready.toFixed(1)}</td><td>${r.need[c].toFixed(1)}</td><td>${fmt(r.owner_hh)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{$('marketSelect').value=tr.dataset.name;renderMetroSelection(tr.dataset.name)});drawAggregates(rows.slice(0,100));setKpis(rows.flatMap(r=>r.zips),'—')}
function renderMetroSelection(name){let m=metros.find(x=>x.name===name);if(!m)return;currentZips=m.zips;setKpis(m.zips,'—');$('mapTitle').textContent=name+' Opportunity';$('mapSub').textContent=`${fmt(m.zips.length)} residential ZIPs in metro crosswalk.`;drawPoints(m.zips);}
async function parentZips(){let p=$('parentType').value,n=$('marketSelect').value;if(p==='metro')return metros.find(x=>x.name===n)?.zips||[];return await dmaZips(n)}
async function renderCounty(){let a=await parentZips(),cs=counties(a),c=$('category').value;currentZips=a;$('countySelect').innerHTML='<option value="all">All counties</option>'+cs.map(x=>`<option value="${x.fips}">${x.name}</option>`).join('');$('tableTitle').textContent='Local Opportunity Rankings';$('tableSub').textContent='Counties inside the selected parent market.';$('thead').innerHTML='<tr><th>County</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th></tr>';$('tbody').innerHTML=cs.slice(0,+$('topN').value).map(x=>`<tr data-fips="${x.fips}"><td>${x.name}</td><td class="score">${x.score[c].toFixed(1)}</td><td>${x.replacement_ready.toFixed(1)}</td><td>${x.need[c].toFixed(1)}</td><td>${fmt(x.owner_hh)}</td></tr>`).join('');$('tbody').querySelectorAll('tr').forEach(tr=>tr.onclick=()=>{$('countySelect').value=tr.dataset.fips;renderCountySelection()});drawAggregates(cs);let scar=$('parentType').value==='dma'?dmas.find(d=>d.dma===$('marketSelect').value)?.[c]?.index||'—':'—';setKpis(a,scar)}
function renderCountySelection(){let f=$('countySelect').value,a=f==='all'?currentZips:currentZips.filter(z=>z.fips===f);drawPoints(a);setKpis(a,$('kScar').textContent)}
async function renderZIP(){if($('zipMode').value==='radius')return renderRadius();let a=await parentZips(),cs=counties(a),prior=$('countySelect').value;$('countySelect').innerHTML='<option value="all">All counties</option>'+cs.map(x=>`<option value="${x.fips}">${x.name}</option>`).join('');if([...$('countySelect').options].some(o=>o.value===prior))$('countySelect').value=prior;let f=$('countySelect').value;if(f&&f!=='all')a=a.filter(z=>z.fips===f);currentZips=a;renderZipTable(a);drawPoints(a);let c=$('category').value,scar=$('parentType').value==='dma'?dmas.find(d=>d.dma===$('marketSelect').value)?.[c]?.index||'—':'—';setKpis(a,scar)}
function renderZipTable(a){let c=$('category').value,rows=a.slice().sort((x,y)=>y.score[c]-x.score[c]);$('tableTitle').textContent='Neighborhood Targeting Rankings';$('tableSub').textContent='Actionable residential ZIP opportunity within the selected market.';$('thead').innerHTML='<tr><th>ZIP</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th><th>Older Homes</th><th>Long Residence</th></tr>';$('tbody').innerHTML=rows.slice(0,+$('topN').value).map(z=>`<tr><td>${z.zip}</td><td class="score">${z.score[c].toFixed(1)}</td><td>${z.replacement_ready.toFixed(1)}</td><td>${z.need[c].toFixed(1)}</td><td>${fmt(z.owner_hh)}</td><td>${z.old_rate.toFixed(1)}%</td><td>${z.tenure_rate.toFixed(1)}%</td></tr>`).join('')}
function renderRadius(){let center=zips.find(z=>z.zip===zip5($('centerZip').value));if(!center){$('tableTitle').textContent='Neighborhood Targeting — Radius';$('tableSub').textContent='Enter a valid residential center ZIP.';return}let miles=+$('radius').value,a=zips.filter(z=>hav(center,z)<=miles),c=$('category').value;a.sort((x,y)=>y.score[c]-x.score[c]);currentZips=a;$('tableTitle').textContent=`ZIPs within ${miles} miles of ${center.zip}`;$('tableSub').textContent='All residential ZIP centroids within the selected radius.';$('thead').innerHTML='<tr><th>ZIP</th><th>Opportunity</th><th>Replacement-Ready</th><th>Need</th><th>Owner HH</th><th>Miles</th></tr>';$('tbody').innerHTML=a.slice(0,+$('topN').value).map(z=>`<tr><td>${z.zip}</td><td class="score">${z.score[c].toFixed(1)}</td><td>${z.replacement_ready.toFixed(1)}</td><td>${z.need[c].toFixed(1)}</td><td>${fmt(z.owner_hh)}</td><td>${hav(center,z).toFixed(1)}</td></tr>`).join('');drawPoints(a);L.circle([center.lat,center.lon],{radius:miles*1609.344,color:'#0d5f9c',weight:2,fill:false,dashArray:'5 5'}).addTo(layerGroup);setKpis(a,'—')}
function drawAggregates(a){layerGroup.clearLayers();let b=[];for(const x of a){L.circleMarker([x.lat,x.lon],{radius:Math.max(5,Math.min(18,4+Math.sqrt(x.owner_hh)/25)),color:'#fff',weight:1,fillColor:color(mapVal(x)),fillOpacity:.85}).bindTooltip(`<b>${x.name}</b><br>Opportunity ${x.score[$('category').value].toFixed(1)}<br>Owner HH ${fmt(x.owner_hh)}`).addTo(layerGroup);b.push([x.lat,x.lon])}if(b.length)map.fitBounds(b,{padding:[20,20]})}
function drawPoints(a){layerGroup.clearLayers();let b=[];for(const z of a.slice(0,2000)){let v=mapVal(z);L.circleMarker([z.lat,z.lon],{radius:4.5,color:'#fff',weight:.5,fillColor:color(v),fillOpacity:.82}).bindTooltip(`<b>${z.zip}</b><br>Opportunity ${z.score[$('category').value].toFixed(1)}<br>Replacement-Ready ${z.replacement_ready.toFixed(1)}<br>Owner HH ${fmt(z.owner_hh)}`).addTo(layerGroup);b.push([z.lat,z.lon])}if(b.length)map.fitBounds(b,{padding:[15,15]})}
function updateControls(){let g=$('geo').value,isSub=g==='county'||g==='zip';$('parentCtl').classList.toggle('hidden',!isSub);$('countyCtl').classList.toggle('hidden',g!=='county'&&(g!=='zip'||$('zipMode').value==='radius'));$('zipModeCtl').classList.toggle('hidden',g!=='zip');$('radiusCtl').classList.toggle('hidden',!(g==='zip'&&$('zipMode').value==='radius'));$('marketCtl').classList.toggle('hidden',g==='zip'&&$('zipMode').value==='radius');if(g==='dma')$('marketLabel').textContent='DMA';if(g==='metro')$('marketLabel').textContent='Metro';populateMarkets();renderCurrent()}
async function renderCurrent(){let g=$('geo').value;if(g==='dma'){renderDMA();$('mapTitle').textContent='U.S. Media Market Opportunity';$('mapSub').textContent='Click a market on the map or ranking to inspect it.';else if(g==='metro'){renderMetroList();if($('marketSelect').value)renderMetroSelection($('marketSelect').value)}else if(g==='county')await renderCounty();else await renderZIP()}



async function fetchJSON(url,label){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${label} failed (${r.status})`);return r.json()}function loadError(msg){$('marketSelect').innerHTML='<option value="">Data unavailable</option>';$('mapSub').textContent=msg;$('tableSub').textContent='Refresh the page. If the problem continues, verify the GitHub Pages data files.';console.error(msg)}async function init(){initMap();$('marketSelect').innerHTML='<option value="">Loading market data…</option>';try{const core=await Promise.all([fetchJSON('zips.json','ZIP data'),fetchJSON('dma.json','DMA data')]);zips=core[0];dmas=core[1];for(const z of zips){z.zip=zip5(z.zip);z.fips=String(z.fips??'').padStart(5,'0')}if(!zips.length||!dmas.length)throw new Error('Core market data is empty');try{metroMap=await fetchJSON('metro-map.json','Metro data')}catch(e){metroMap={};console.warn(e.message)}attachMetro();updateControls()}catch(e){loadError('Unable to load core market data: '+e.message);return}try{dmaGeo=await fetchJSON('https://raw.githubusercontent.com/Mrk-Nguyen/dmamap/master/nielsengeo.json','DMA boundaries');renderCurrent()}catch(e){console.warn('DMA boundary unavailable',e);$('mapSub').textContent='Market data loaded. DMA boundary map is temporarily unavailable.'}$('geo').onchange=updateControls;$('parentType').onchange=()=>{populateMarkets();renderCurrent()};$('marketSelect').onchange=renderCurrent;$('countySelect').onchange=()=>{$('geo').value==='county'?renderCountySelection():renderZIP()};$('zipMode').onchange=updateControls;$('centerZip').onchange=renderRadius;$('radius').onchange=renderRadius;$('category').onchange=()=>{attachMetro();populateMarkets();renderCurrent()};$('topN').onchange=renderCurrent}init();


function syncAnalysisUI(){
 const media=$('geo').value==='dma';
 $('where').style.display=media?'none':'';
 if(media){$('mapTitle').textContent='U.S. Media Market Opportunity';$('mapSub').textContent='Click a market on the map or ranking to inspect it.';}
}
$('geo').addEventListener('change',syncAnalysisUI);syncAnalysisUI();

function updateSeasonal(){
 const lead=$('seasonHorizon').value, type=$('seasonType').value;
 const h=lead==='01'?'Next 3 Months':'Next 6 Months';
 const label=type==='temp'?'Temperature':'Precipitation';
 $('seasonTitle').textContent=h+' · '+label;
 // CPC's official seasonal image endpoint. The six-month planning view uses the later overlapping 3-month outlook.
 const url=`https://www.cpc.ncep.noaa.gov/products/predictions/long_range/lead${lead}/off${lead}_${type}.gif`;
 const img=$('seasonImg'), fb=$('seasonFallback');
 fb.style.display='flex'; img.style.display='none';
 img.onload=()=>{fb.style.display='none';img.style.display='block'};
 img.onerror=()=>{fb.textContent='NOAA outlook is temporarily unavailable. Please try again later.'};
 img.src=url+'?v='+Date.now();
}
$('seasonHorizon').onchange=updateSeasonal;$('seasonType').onchange=updateSeasonal;updateSeasonal();
